#!/bin/bash

p=`basename $0`

# A string with command options
options=$@

# An array with all the arguments
arguments=($options)

# Loop index
index=0

for argument in $options; do
    # Incrementing index
    index=`expr $index + 1`

    # The conditions
    case $argument in
	--in-dir) 
	    VMINPUTDIR=${arguments[index]};;
	--out-dir) 
	    VMOUTPUTDIR=${arguments[index]};;
	--base-dir)
	    echo "";;
	--plat-name)
	    export VMPLATNAME=${arguments[index]};;
	--plat-uuid)
	    VMPLATUUID=${arguments[index]};;
	--os-pkg-install-cmd)
	    export VMOSPACKAGEINSTALL=${arguments[index]};;
	--version)
	    exit 0;;
    esac
done

## XXX can also be $HOME
export SWAMP_DIR=/opt/swamp-base

function untar {
    sudo tar -xpf "$1" --directory="$2" && { tar tf "$1" | cut -d / -f 1 | uniq; }
}

function get_conf_value {
	local param="$1"
	local conf_file="$2"

	## [ space tab ] portable regex
	## was -r extended regex and '\s' for whitespace, and () unescaped
	## \([]*\)* vs + because it might be empty, or null
	sed -n "/^${param}[ 	]*=/ s@^${param}[ 	]*=[ 	]*\([^ 	]*\)[ 	]*@\1@p" "$conf_file"
}

if [[ -z "$VMOSPACKAGEINSTALL" ]]; then
    export VMOSPACKAGEINSTALL="$VMINPUTDIR/install-dependencies"
fi

if [[ -z "$VMPLATNAME" ]]; then
    export VMPLATNAME=$("$VMINPUTDIR/get-platform")
fi

set -x -v

OPT_SWAMP_DIR=/opt/swamp
OPT_SWAMP_BASE_DIR=/opt/swamp-base

[[ ! -d $OPT_SWAMP_BASE_DIR ]] && mkdir $OPT_SWAMP_BASE_DIR

if [[ "$(uname -p)" == "x86_64" ]]; then 
	NODE_ARCHIVE="$VMINPUTDIR/node-v6.4.0-linux-x64.tar.xz"
else
	NODE_ARCHIVE="$VMINPUTDIR/node-v6.4.0-linux-x86.tar.xz"
fi

NODE_DIR=$(untar $NODE_ARCHIVE $OPT_SWAMP_BASE_DIR)
[[ $? == 0 ]] && export PATH="$OPT_SWAMP_BASE_DIR/$NODE_DIR/bin:$PATH"

if [[ -f "$VMINPUTDIR/python-2-bin.tar.gz" ]]; then
    sudo tar xpf "$VMINPUTDIR/python-2-bin.tar.gz" -C $OPT_SWAMP_DIR \
        && export SWAMP_PYTHON2_HOME="$OPT_SWAMP_DIR/python2"
fi

if [[ -f "$VMINPUTDIR/python-3-bin.tar.gz" ]]; then
    sudo tar xpf "$VMINPUTDIR/python-3-bin.tar.gz" -C $OPT_SWAMP_DIR \
        && export SWAMP_PYTHON3_HOME="$OPT_SWAMP_DIR/python3"
fi

echo
echo $p: setup environment
export BUILD_DIR="${HOME}/build"
export TOOL_DIR="${HOME}/tool"
export RESULTS_DIR="${HOME}/results"
export SCRIPTS_DIR=${HOME}/$(untar "${VMINPUTDIR}/scripts.tar.gz" "$PWD")
#export SCRIPTS_DIR="${HOME}/scripts"
export PYTHONPATH="${SCRIPTS_DIR}/lib:${PYTHONPATH}"

echo
echo $p: start script_assess
python3 -B -m script_assess --printVersion --printPlatform ${VMINPUTDIR} ${VMOUTPUTDIR} ${BUILD_DIR} ${TOOL_DIR} ${RESULTS_DIR}
