
# gencmd_parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '1E0349E66FEF050B98C84274B5005B31'
    
_lr_action_items = {'QSTRING':([0,9,17,18,23,],[1,1,1,1,1,]),'PARAM':([0,9,17,18,23,],[3,3,3,3,3,]),'STRING':([0,9,17,18,23,],[6,6,6,6,6,]),'$end':([8,9,12,13,18,24,],[0,-20,-6,-1,-20,-5,]),'NEWLINE':([1,2,3,4,5,6,7,10,11,14,15,16,17,19,20,21,22,25,],[-12,-3,-19,-2,9,-11,-4,18,-10,-7,-8,-9,-13,-18,-16,-14,-17,-15,]),'OPTIONNAME':([9,18,],[17,17,]),'SEPERATER':([17,],[23,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'string':([0,9,17,18,23,],[2,15,19,15,19,]),'param':([0,9,17,18,23,],[4,11,20,11,20,]),'executable':([0,],[5,]),'arg':([9,18,],[10,10,]),'empty':([9,18,],[12,12,]),'quotedstring':([0,9,17,18,23,],[7,16,22,16,22,]),'option':([9,18,],[14,14,]),'optionarg':([17,23,],[21,25,]),'command':([0,],[8,]),'args':([9,18,],[13,24,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> command","S'",1,None,None,None),
  ('command -> executable NEWLINE args','command',3,'p_command','gencmd.py',73),
  ('executable -> param','executable',1,'p_executable','gencmd.py',78),
  ('executable -> string','executable',1,'p_executable','gencmd.py',79),
  ('executable -> quotedstring','executable',1,'p_executable','gencmd.py',80),
  ('args -> arg NEWLINE args','args',3,'p_args','gencmd.py',86),
  ('args -> empty','args',1,'p_args_empty','gencmd.py',91),
  ('arg -> option','arg',1,'p_arg','gencmd.py',96),
  ('arg -> string','arg',1,'p_arg','gencmd.py',97),
  ('arg -> quotedstring','arg',1,'p_arg','gencmd.py',98),
  ('arg -> param','arg',1,'p_arg','gencmd.py',99),
  ('string -> STRING','string',1,'p_string','gencmd.py',105),
  ('quotedstring -> QSTRING','quotedstring',1,'p_quotedstring','gencmd.py',110),
  ('option -> OPTIONNAME','option',1,'p_option','gencmd.py',115),
  ('option -> OPTIONNAME optionarg','option',2,'p_option_value','gencmd.py',120),
  ('option -> OPTIONNAME SEPERATER optionarg','option',3,'p_option_sep_value','gencmd.py',125),
  ('optionarg -> param','optionarg',1,'p_optionarg','gencmd.py',130),
  ('optionarg -> quotedstring','optionarg',1,'p_optionarg','gencmd.py',131),
  ('optionarg -> string','optionarg',1,'p_optionarg','gencmd.py',132),
  ('param -> PARAM','param',1,'p_param','gencmd.py',138),
  ('empty -> <empty>','empty',0,'p_empty','gencmd.py',144),
]
